version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  python-runner:
    build:
      context: ./docker
      dockerfile: python.Dockerfile
    image: python-runner

  js-runner:
    build:
      context: ./docker
      dockerfile: javascript.Dockerfile
    image: js-runner

  cpp-runner:
    build:
      context: ./docker
      dockerfile: cpp.Dockerfile
    image: cpp-runner

  go-runner:
    build:
      context: ./docker
      dockerfile: go.Dockerfile
    image: go-runner

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run worker
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - code-exec-share:/shared

volumes:
  code-exec-share:
    name: code-exec-share
