version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  python-runner:
    build:
      context: ./docker
      dockerfile: python.Dockerfile
    image: python-runner

  js-runner:
    build:
      context: ./docker
      dockerfile: javascript.Dockerfile
    image: js-runner

  cpp-runner:
    build:
      context: ./docker
      dockerfile: cpp.Dockerfile
    image: cpp-runner

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run worker
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - code-exec-share:/shared
      - ./service-account.json:/app/service-account.json
    environment:
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    command: node worker/bridge.js
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      - ./service-account.json:/app/service-account.json

volumes:
  code-exec-share:
    name: code-exec-share
